### ISSUE TITLE
Server doesn't find running mpv instance 

### ISSUE THREAD

**Issue by Uatschitchun** [mcastorina/mpv-remote-app#13]
Checked out, pip install requirements, start mpv as stated in Readme, but server.py doesn't recognize the running instance and starts its own. So no control of running instance possible 

If server starts own mpv instance, even with using '-r path/to/media', hitting library in app results in nothing. I can see the server is "browsing" the path, but app doesn't display anything. So no control possible :-(

**Comment by mcastorina** [comment]
Thanks for opening an issue! I moved the second paragraph into a separate issue ( #14 ) and we will focus on the server not finding the running mpv instance here.

For the python script to find a running instance, it must be started with the `--input-ipc-flag`.

1. Could you please provide the mpv command you are running?
2. What OS are you using?

Thanks

**Comment by Uatschitchun** [comment]
I started the server without a running mpv instance and 'ps aux | grep mpv'. I used exactly the same command

**Comment by Uatschitchun** [comment]
This is the command I started mov with:
`mpv --no-terminal --input-ipc-server /tmp/mpvsocket --idle`
I even tried with a file specified instead of --idle but that doesn't help

**Comment by mcastorina** [comment]
I just pushed a commit 1f567d52bfd125d581bfa37bd9a3832ad249c564 that should fix the problem. Please verify the issue has been resolved in the new server.py.
