### ISSUE TITLE
Error setting property - unable to control mpv

### ISSUE THREAD

**Issue by SPDurkee** [mcastorina/mpv-remote-app#15]
I am able to communicate from the Android app to the python server, however every command sent to mpv comes back failed. Here is some of the output:
{'time': 1546583672857, 'value': True, 'command': 'set', 'property': 'pause'}
Error setting property: pause = True
ACK {"message": null, "time": 1546583672952, "action": 1546583672857, "result": false}
{'time': 1546583701036, 'value': True, 'command': 'set', 'property': 'pause'}
Error setting property: pause = True
ACK {"message": null, "time": 1546583701129, "action": 1546583701036, "result": false}
{'time': 1546583701852, 'value': True, 'command': 'set', 'property': 'pause'}
Error setting property: pause = True
ACK {"message": null, "time": 1546583701944, "action": 1546583701852, "result": false}
{'time': 1546583745526, 'value': 59, 'command': 'set', 'property': 'volume'}
Error setting property: volume = 59
ACK {"message": null, "time": 1546583745618, "action": 1546583745526, "result": false}
{'pre': None, 'post': '%', 'time': 1546583745542, 'command': 'show', 'property': 'volume'}
ACK {"message": "", "time": 1546583745630, "action": 1546583745542, "result": true}
{'time': 1546583745550, 'value': True, 'command': 'set', 'property': 'pause'}
Error setting property: pause = True
ACK {"message": null, "time": 1546583745640, "action": 1546583745550, "result": false}
{'time': 1546583745932, 'value': True, 'command': 'set', 'property': 'pause'}
Error setting property: pause = True
ACK {"message": null, "time": 1546583746023, "action": 1546583745932, "result": false}
{'time': 1546583763872, 'value': True, 'command': 'set', 'property': 'fullscreen'}
Error setting property: fullscreen = True
ACK {"message": null, "time": 1546583763966, "action": 1546583763872, "result": false}

I can confirm mpv is started with the --input-ipc-server mpv_socket option.

mpv git-2018-11-18-ce2253b Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Mon Dec 17 05:57:11 UTC 2018
ffmpeg library versions:
   libavutil       56.24.101
   libavcodec      58.42.102
   libavformat     58.24.101
   libswscale      5.4.100
   libavfilter     7.46.101
   libswresample   3.4.100
ffmpeg version: git-2018-12-16-de5e71f

**Comment by mcastorina** [comment]
Currently, commands are sent to mpv via the socat binary. From what you posted, either every command is coming back as failed success from mpv, or the more likely scenario is you do not have socat installed.

Here is an example of using socat to communicate with the IPC socket.

```
» echo '{"command": ["set_property", "pause", true]}' | socat - /tmp/mpvsocket
```

If you _do_ have socat installed, then we will need to modify some code to figure out what's really happening. Let me know, thanks!

**Comment by SPDurkee** [comment]
I did not have socat installed, however installing it did not fix the problem.
When executing the line of code you sent, I received a connect refused error.

Further troubleshooting reveled I had the incorrect socket specified when launching mpv.
Line 18 of server.py states: # mpv needs to be started with the flag --input-ipc-server mpv_socket
The correct flag should be --input-ipc-server /tmp/mpvsocket

Maybe I missed this somewhere, but since launching mpv with this flag is critical to the remote working, I recommend you publish this clearly in the instructions or similar as well as correcting line 18.

Thanks for your help as everything is working now!

**Comment by mcastorina** [comment]
Great, thanks for the feedback!

For future reference, you can start mpv with any named socket as long as you tell the server which file to use (`--mpv-socket` or `-s` flag). The default is `/tmp/mpvsocket` which just makes it easier to start mpv with that.
