### ISSUE TITLE
audio settings

### ISSUE THREAD

**Issue by mcastorina** [mcastorina/mpv-remote-app#17]
add setting in menu to choose which audio track to use

**Comment by mcastorina** [comment]
Merged in commit d297c1031ebefdf6c01f37e00870fabc45e278e6

**Comment by haarp** [comment]
mhh, to be honest, I wouldn't have hidden this and the subtitle selector in the menu. The menu can be cumbersome and this kinda negates the separation of "interactive things on the main screen, settings in the menu". Just my opinion. Cheers :)

**Comment by mcastorina** [comment]
I appreciate a different perspective.

IMO the audio/subtitle track is a setting and not something you interact with often.. why take up space on the main screen for something you set once?
