### ISSUE TITLE
Can't play files with non-ASCII filenames?

### ISSUE THREAD

**Issue by adia** [mcastorina/mpv-remote-app#25]
It seems that non-ASCII filenames cause some trouble to the server - example debug output:

    DEBUG:root:Received: "{"message":"{\"time\":1555279337058,\"command\":\"play\",\"path\":\".\\\/ττ.mkv\"}","hmac":"b66d4189c5170c1b274e8115f7622edb"}"
    INFO:root:Authentication failed for command: "{'message': '{"time":1555279337058,"command":"play","path":".\\/ττ.mkv"}', 'hmac': 'b66d4189c5170c1b274e8115f7622edb'}"

Can't browse non-ASCII directories, either:

    INFO:root:Received command: "{'time': 1555279609126, 'directory': '.', 'command': 'list'}"
    DEBUG:root:Sending ACK: "{"action": 1555279609126, "time": 1555279598434, "result": true, "message": {"directories": ["\u03c4\u03b5\u03c3\u03c4", "test"], "files": []}}"
    DEBUG:root:heartbeat
    DEBUG:root:Received: "{"message":"{\"time\":1555279609962,\"directory\":\".\\\/τεστ\",\"command\":\"list\"}","hmac":"dba7c18b31dbcae8fb505d98acd1b15a"}"
    INFO:root:Authentication failed for command: "{'message': '{"time":1555279609962,"directory":".\\/τεστ","command":"list"}', 'hmac': 'dba7c18b31dbcae8fb505d98acd1b15a'}"

Running with Python 3.7.3 under Gentoo Linux.
Thanks!

**Comment by mcastorina** [comment]
Sorry for the delay. The issue looks like it's with the Android application's HMAC encoding here:
[HMAC.java#L32](https://github.com/mcastorina/mpv-remote-app/blob/master/MpvRemote/app/src/main/java/miccah/laptopremote/HMAC.java#L32)

Changing `message.getBytes("ASCII")` to `message.getBytes("UTF-8")` should solve the problem.

I'll test it out and upload a new snapshot when I confirm it's working.

**Comment by mcastorina** [comment]
Fix has been implemented and the snapshot is updated!
